---
title: "Crafting Audience Engagement in Social Media Conversations: Evidence from the U.S. 2020 Presidential Elections -- Mark Famous Tweets"
author: "Linus Hagemann"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
tweet_usernames <- read.csv('names_of_tweeters_in_order')
media <- read.csv('media.csv')
politicians <- read.csv('politiciancs.csv')
calebrities <- read.csv('celebrities.csv')
```

```{r}
# lowercasing all usernames
media$handle <- tolower(media$handle)
politicians$handle <- tolower(politicians$handle)
calebrities$handle <- tolower(calebrities$handle)
```

```{r}
famous_people <- rbind(media, politicians, calebrities)
```

# Classifying tweets

```{r}
# 0 - not famous
# 1 - famous 
# 2 - famous over 100 000
# 3 - famous over 1 000 000
# 4 - famous over 50 000 000
# 5 - famous over 100 000 000

categorizeFollowersNumber <- function (username) {
  if(username %in% famous_people$handle){
    followers <- as.integer(gsub("[^0-9.-]", "", famous_people[famous_people$handle==username,]$followers))
    if (followers > 100000000) return(5);
    if (followers > 50000000) return(4);
    if (followers > 1000000) return(3);
    if (followers > 100000) return(2);
    return(1);
  }
  return(0);
}
```

```{r}
isInFamousSample <- sapply(tweet_usernames$x, function(name) ifelse(name %in% famous_people$handle, 1, 0))
famousTweeterLevel <- sapply(tweet_usernames$x, categorizeFollowersNumber)
```

```{r}
tweet_famous_level <- data.frame(isInFamousSample, famousTweeterLevel)
names(tweet_famous_level) <- c('isFamous', 'fameLevel')
write.csv(tweet_famous_level,'tweets_famous.csv')
```


